### ISSUE TITLE
Cannot do final step in [Prerequisites]

### ISSUE THREAD

**Issue by suprimex** [rust-embedded/rust-raspi3-OS-tutorials#25]
Cannot do final step in [Prerequisites]:
cmd: rustup component add clippy-preview --toolchain=nightly
error: component 'clippy' for target 'x86_64-unknown-linux-gnu' is unavailable for download for channel 'nightly'

**Comment by andre-richter** [comment]
Updated the README accordingly. Please give it a try :)
