### ISSUE TITLE
Suggested Paragraph on Docker

### ISSUE THREAD

**Issue by rahealy** [rust-embedded/rust-raspi3-OS-tutorials#28]
I'm uncertain if a github pull request or an issue (or a mailing list?) is appropriate for this so I'm just putting it here. Please let me know if it needs to go somewhere else.

Based on my own experience working through the tutorials I think a small paragraph about docker might be desirable. Here's a possible suggestion:

> ### Docker
> 
> To facilitate downloading, building and running the required development tools some of the tutorials in this repository use a piece of software called docker. While docker specifics are outside of this tutorial's scope it is worth mentioning that human readable docker configuration files named "Dockerfile" exist in various repository sub-directories. These files may be of interest to those who want details about what will happen when docker is invoked.

**Comment by andre-richter** [comment]
I pushed a change based on your suggestion. Thanks!
